---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kassette-camunda-agent.fullname" . }}-config
  labels:
    {{- include "kassette-camunda-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
