apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.rpcPort }}
      targetPort: {{ .Values.rpcPort }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.statusPort }}
      targetPort: {{ .Values.statusPort }}
      protocol: TCP
      name: status
  selector:
    {{- include "graph-node.selectorLabels" . | nindent 4 }}
