# Default values for graph-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: graphprotocol/graph-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

postgresCredentials:
  postgres_host: postgres-postgresql
  postgres_user: graph
  postgres_pass: graph
  postgres_db: graph

httpPort: 8000
rpcPort: 8020
metricsPort: 8040
statusPort: 8030

statefulSet:    
  env:
    GRAPH_LOG: debug
    RUST_LOG: INFO
    BLOCK_INGESTOR: index-node-0
    GRAPH_ETH_CALL_GAS: "50000000"
    GRAPH_GETH_ETH_CALL_ERRORS: "out of gas"
    ETHEREUM_TRACE_STREAM_STEP_SIZE: "50"
    ETHEREUM_BLOCK_BATCH_SIZE: "10"
    ETHEREUM_RPC_MAX_PARALLEL_REQUESTS: "64"
    GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: "500"
    GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: "200"
    GRAPH_KILL_IF_UNRESPONSIVE: "true"
    GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: "true"
    EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE: "synced"
    node_role: index-node

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "8040"
  prometheus.io/scrape: "true"

